const errorHandler = (error, req, res, next) => {
    //error generated by Multer if file size exceeds the limit.
    if (error.code == "LIMIT_FILE_SIZE") {
      res.status(413).send("File size limit exceeded.");
    }
    next();
  };

module.exports = errorHandler;