const errorHandler = (error, req, res, next) => {
  console.log("we just saw an error")
  console.log(error);

    //error generated by Multer if file size exceeds the limit.
    if (error.code == "LIMIT_FILE_SIZE") {
      res.status(413).send({errorCode: "LIMIT_FILE_SIZE"});
    }

    //custom error if upload file type is not supported
    if (error.code == "FILE_TYPE_NOT_SUPPORTED") {
      res.status(413).send({errorCode: error.code});
    }

    //Multer error if number of files exceeds the limit
    if (error.code == "LIMIT_FILE_COUNT") {
      res.status(413).send({errorCode: error.code});
    }

    next();
  };

module.exports = errorHandler;